
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'BackToTopButton': typeof import("../components/BackToTopButton.vue")['default']
    'BaseInput': typeof import("../components/BaseInput.vue")['default']
    'BaseTextarea': typeof import("../components/BaseTextarea.vue")['default']
    'CasesBlock': typeof import("../components/CasesBlock.vue")['default']
    'CertificatesBlock': typeof import("../components/CertificatesBlock.vue")['default']
    'CookiesComponent': typeof import("../components/CookiesComponent.vue")['default']
    'FaqCard': typeof import("../components/FaqCard.vue")['default']
    'FooterComponent': typeof import("../components/FooterComponent.vue")['default']
    'FormComponent': typeof import("../components/FormComponent.vue")['default']
    'FormModal': typeof import("../components/FormModal.vue")['default']
    'HeaderComponent': typeof import("../components/HeaderComponent.vue")['default']
    'IconArrow': typeof import("../components/Icon/Arrow.vue")['default']
    'IconArrowThin': typeof import("../components/Icon/ArrowThin.vue")['default']
    'IconBurger': typeof import("../components/Icon/Burger.vue")['default']
    'IconCheck': typeof import("../components/Icon/Check.vue")['default']
    'IconCode': typeof import("../components/Icon/Code.vue")['default']
    'IconCross': typeof import("../components/Icon/Cross.vue")['default']
    'IconCrossCircle': typeof import("../components/Icon/CrossCircle.vue")['default']
    'IconFileCircle': typeof import("../components/Icon/FileCircle.vue")['default']
    'IconLogo': typeof import("../components/Icon/Logo.vue")['default']
    'IconLogoBig': typeof import("../components/Icon/LogoBig.vue")['default']
    'IconLogoFile': typeof import("../components/Icon/LogoFile.vue")['default']
    'IconTelegram': typeof import("../components/Icon/Telegram.vue")['default']
    'IconWhatsapp': typeof import("../components/Icon/Whatsapp.vue")['default']
    'InfoBlock': typeof import("../components/InfoBlock.vue")['default']
    'KeyPractices': typeof import("../components/KeyPractices.vue")['default']
    'LoadingComponent': typeof import("../components/LoadingComponent.vue")['default']
    'MainBlock': typeof import("../components/MainBlock.vue")['default']
    'MainMenu': typeof import("../components/MainMenu.vue")['default']
    'NumbersComponent': typeof import("../components/NumbersComponent.vue")['default']
    'OurTeam': typeof import("../components/OurTeam.vue")['default']
    'PayFile': typeof import("../components/PayFile.vue")['default']
    'PayModal': typeof import("../components/PayModal.vue")['default']
    'ServiceOrder': typeof import("../components/ServiceOrder.vue")['default']
    'VideoSlider': typeof import("../components/VideoSlider.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyBackToTopButton': typeof import("../components/BackToTopButton.vue")['default']
    'LazyBaseInput': typeof import("../components/BaseInput.vue")['default']
    'LazyBaseTextarea': typeof import("../components/BaseTextarea.vue")['default']
    'LazyCasesBlock': typeof import("../components/CasesBlock.vue")['default']
    'LazyCertificatesBlock': typeof import("../components/CertificatesBlock.vue")['default']
    'LazyCookiesComponent': typeof import("../components/CookiesComponent.vue")['default']
    'LazyFaqCard': typeof import("../components/FaqCard.vue")['default']
    'LazyFooterComponent': typeof import("../components/FooterComponent.vue")['default']
    'LazyFormComponent': typeof import("../components/FormComponent.vue")['default']
    'LazyFormModal': typeof import("../components/FormModal.vue")['default']
    'LazyHeaderComponent': typeof import("../components/HeaderComponent.vue")['default']
    'LazyIconArrow': typeof import("../components/Icon/Arrow.vue")['default']
    'LazyIconArrowThin': typeof import("../components/Icon/ArrowThin.vue")['default']
    'LazyIconBurger': typeof import("../components/Icon/Burger.vue")['default']
    'LazyIconCheck': typeof import("../components/Icon/Check.vue")['default']
    'LazyIconCode': typeof import("../components/Icon/Code.vue")['default']
    'LazyIconCross': typeof import("../components/Icon/Cross.vue")['default']
    'LazyIconCrossCircle': typeof import("../components/Icon/CrossCircle.vue")['default']
    'LazyIconFileCircle': typeof import("../components/Icon/FileCircle.vue")['default']
    'LazyIconLogo': typeof import("../components/Icon/Logo.vue")['default']
    'LazyIconLogoBig': typeof import("../components/Icon/LogoBig.vue")['default']
    'LazyIconLogoFile': typeof import("../components/Icon/LogoFile.vue")['default']
    'LazyIconTelegram': typeof import("../components/Icon/Telegram.vue")['default']
    'LazyIconWhatsapp': typeof import("../components/Icon/Whatsapp.vue")['default']
    'LazyInfoBlock': typeof import("../components/InfoBlock.vue")['default']
    'LazyKeyPractices': typeof import("../components/KeyPractices.vue")['default']
    'LazyLoadingComponent': typeof import("../components/LoadingComponent.vue")['default']
    'LazyMainBlock': typeof import("../components/MainBlock.vue")['default']
    'LazyMainMenu': typeof import("../components/MainMenu.vue")['default']
    'LazyNumbersComponent': typeof import("../components/NumbersComponent.vue")['default']
    'LazyOurTeam': typeof import("../components/OurTeam.vue")['default']
    'LazyPayFile': typeof import("../components/PayFile.vue")['default']
    'LazyPayModal': typeof import("../components/PayModal.vue")['default']
    'LazyServiceOrder': typeof import("../components/ServiceOrder.vue")['default']
    'LazyVideoSlider': typeof import("../components/VideoSlider.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const BackToTopButton: typeof import("../components/BackToTopButton.vue")['default']
export const BaseInput: typeof import("../components/BaseInput.vue")['default']
export const BaseTextarea: typeof import("../components/BaseTextarea.vue")['default']
export const CasesBlock: typeof import("../components/CasesBlock.vue")['default']
export const CertificatesBlock: typeof import("../components/CertificatesBlock.vue")['default']
export const CookiesComponent: typeof import("../components/CookiesComponent.vue")['default']
export const FaqCard: typeof import("../components/FaqCard.vue")['default']
export const FooterComponent: typeof import("../components/FooterComponent.vue")['default']
export const FormComponent: typeof import("../components/FormComponent.vue")['default']
export const FormModal: typeof import("../components/FormModal.vue")['default']
export const HeaderComponent: typeof import("../components/HeaderComponent.vue")['default']
export const IconArrow: typeof import("../components/Icon/Arrow.vue")['default']
export const IconArrowThin: typeof import("../components/Icon/ArrowThin.vue")['default']
export const IconBurger: typeof import("../components/Icon/Burger.vue")['default']
export const IconCheck: typeof import("../components/Icon/Check.vue")['default']
export const IconCode: typeof import("../components/Icon/Code.vue")['default']
export const IconCross: typeof import("../components/Icon/Cross.vue")['default']
export const IconCrossCircle: typeof import("../components/Icon/CrossCircle.vue")['default']
export const IconFileCircle: typeof import("../components/Icon/FileCircle.vue")['default']
export const IconLogo: typeof import("../components/Icon/Logo.vue")['default']
export const IconLogoBig: typeof import("../components/Icon/LogoBig.vue")['default']
export const IconLogoFile: typeof import("../components/Icon/LogoFile.vue")['default']
export const IconTelegram: typeof import("../components/Icon/Telegram.vue")['default']
export const IconWhatsapp: typeof import("../components/Icon/Whatsapp.vue")['default']
export const InfoBlock: typeof import("../components/InfoBlock.vue")['default']
export const KeyPractices: typeof import("../components/KeyPractices.vue")['default']
export const LoadingComponent: typeof import("../components/LoadingComponent.vue")['default']
export const MainBlock: typeof import("../components/MainBlock.vue")['default']
export const MainMenu: typeof import("../components/MainMenu.vue")['default']
export const NumbersComponent: typeof import("../components/NumbersComponent.vue")['default']
export const OurTeam: typeof import("../components/OurTeam.vue")['default']
export const PayFile: typeof import("../components/PayFile.vue")['default']
export const PayModal: typeof import("../components/PayModal.vue")['default']
export const ServiceOrder: typeof import("../components/ServiceOrder.vue")['default']
export const VideoSlider: typeof import("../components/VideoSlider.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyBackToTopButton: typeof import("../components/BackToTopButton.vue")['default']
export const LazyBaseInput: typeof import("../components/BaseInput.vue")['default']
export const LazyBaseTextarea: typeof import("../components/BaseTextarea.vue")['default']
export const LazyCasesBlock: typeof import("../components/CasesBlock.vue")['default']
export const LazyCertificatesBlock: typeof import("../components/CertificatesBlock.vue")['default']
export const LazyCookiesComponent: typeof import("../components/CookiesComponent.vue")['default']
export const LazyFaqCard: typeof import("../components/FaqCard.vue")['default']
export const LazyFooterComponent: typeof import("../components/FooterComponent.vue")['default']
export const LazyFormComponent: typeof import("../components/FormComponent.vue")['default']
export const LazyFormModal: typeof import("../components/FormModal.vue")['default']
export const LazyHeaderComponent: typeof import("../components/HeaderComponent.vue")['default']
export const LazyIconArrow: typeof import("../components/Icon/Arrow.vue")['default']
export const LazyIconArrowThin: typeof import("../components/Icon/ArrowThin.vue")['default']
export const LazyIconBurger: typeof import("../components/Icon/Burger.vue")['default']
export const LazyIconCheck: typeof import("../components/Icon/Check.vue")['default']
export const LazyIconCode: typeof import("../components/Icon/Code.vue")['default']
export const LazyIconCross: typeof import("../components/Icon/Cross.vue")['default']
export const LazyIconCrossCircle: typeof import("../components/Icon/CrossCircle.vue")['default']
export const LazyIconFileCircle: typeof import("../components/Icon/FileCircle.vue")['default']
export const LazyIconLogo: typeof import("../components/Icon/Logo.vue")['default']
export const LazyIconLogoBig: typeof import("../components/Icon/LogoBig.vue")['default']
export const LazyIconLogoFile: typeof import("../components/Icon/LogoFile.vue")['default']
export const LazyIconTelegram: typeof import("../components/Icon/Telegram.vue")['default']
export const LazyIconWhatsapp: typeof import("../components/Icon/Whatsapp.vue")['default']
export const LazyInfoBlock: typeof import("../components/InfoBlock.vue")['default']
export const LazyKeyPractices: typeof import("../components/KeyPractices.vue")['default']
export const LazyLoadingComponent: typeof import("../components/LoadingComponent.vue")['default']
export const LazyMainBlock: typeof import("../components/MainBlock.vue")['default']
export const LazyMainMenu: typeof import("../components/MainMenu.vue")['default']
export const LazyNumbersComponent: typeof import("../components/NumbersComponent.vue")['default']
export const LazyOurTeam: typeof import("../components/OurTeam.vue")['default']
export const LazyPayFile: typeof import("../components/PayFile.vue")['default']
export const LazyPayModal: typeof import("../components/PayModal.vue")['default']
export const LazyServiceOrder: typeof import("../components/ServiceOrder.vue")['default']
export const LazyVideoSlider: typeof import("../components/VideoSlider.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
